# Generated by Django 5.1.15 on 2026-09-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('categoria', models.CharField(choices=[('general', 'General'), ('rrhh', 'Recursos humanos'), ('ti', 'Tecnología'), ('eventos', 'Eventos')], default='general', max_length=20, verbose_name='categoría')),
                ('fijado', models.BooleanField(default=False, help_text='Mostrar siempre arriba', verbose_name='fijado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-fijado', '-creado_en'],
            },
        ),
    ]
