# Generated by Django 5.1.15 on 2026-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('url', models.CharField(help_text='Puede ser una ruta interna (/admin/) o una URL completa (https://...)', max_length=300, verbose_name='URL')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'enlace del sitio',
                'verbose_name_plural': 'enlaces del sitio',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='título')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'imagen de galería',
                'verbose_name_plural': 'imágenes de galería',
                'ordering': ['orden', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='categoria',
            field=models.CharField(choices=[('general', 'General'), ('rrhh', 'Recursos humanos'), ('ti', 'Tecnología'), ('eventos', 'Eventos'), ('para_ti', 'Para ti')], default='general', max_length=20, verbose_name='categoría'),
        ),
    ]
